### ISSUE TITLE
webpack 整套方案的支持

### ISSUE THREAD

**Issue by ustbhuangyi** [sexdevil/LSLoader#1]
希望基于 webpack 提供一整套方案，不依赖 gulp

**Comment by yugasun** [comment]
+1
PS: 麻烦更新下README，实在太难看了.....

**Comment by sexdevil** [comment]
好的 等我最近忙忘手头工作的 文档太老了

**Comment by sexdevil** [comment]
好的 等我最近忙忘手头工作的 文档太老了

**Comment by sexdevil** [comment]
最新的代码把构建流程都放入了webpack.config.js  一个命令就完成所有步骤。closed
