### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by jiajianrong** [sexdevil/LSLoader#4]
1，请问依赖分析是针对uglify之后的代码吗？我看astbuild里貌似是require了uglify，不是acorn
2，ast之后，如何一一匹配 模块id和js绝对路径？  不同项目的路径不一样，涉及发布测试环境和真实上线路径，感觉很麻烦啊

**Comment by sexdevil** [comment]
1、依赖分析是uglify之前的
2、路径匹配是要通过gulp/webpack 原有构建流程生成的manfest.json表去匹配的，通常情况只是线上环境使用缓存，测试环境还是裸JS方便调试和charles代理

**Comment by jiajianrong** [comment]
嗯，2还是很麻烦，一旦规定好了目录结构就不动了
在多个不同项目中推广特别困难，因为牵扯到不同项目的编译上线步骤

**Comment by sexdevil** [comment]
是的 如果对路径侵入过多就需要公司级别的统一前端构建规则，如果对项目灵活那就需要接入方多配置，看情况自己定义，离线缓存只是一种思路
