### ISSUE TITLE
项目没有跑起来！是我本地环境问题还是代码太旧

### ISSUE THREAD

**Issue by sunlianlong** [sexdevil/LSLoader#7]
很抱歉，我用git下载代码到本地后 npm install  无法把全部依赖下载下来，并且单独把报错的依赖包下载下来后，依然没有成功打包出来一个demo出来，希望维护者能够解答一下或者提供一个最小可运行demo.谢谢。

本地环境：
```
node v9.11.1
npm  5.6.0
```

**Comment by sexdevil** [comment]
不好意思9月份太忙了没看，更新了package.json 重新拉下master分支按照文档说明
npm install 
gulp 
webpack
node app.js
顺序就可以跑通了

**Comment by sexdevil** [comment]
全部node_modules的打包发到百度网盘了 如果npm方式实在不可以用这个可以看demo
链接: https://pan.baidu.com/s/1XpN2uFZS5R3QNljoFxbJfA 提取码: yh4f
